--- # git server setup
- hosts: webserver
  user: hallo
  sudo: yes
  gather_facts: yes
  tasks:
  - name: installing httpd package
    yum: name=httpd state=installed
    ignore_errors: yes
    
  

